#!/bin/sh
#
# monit-remote monit remote configuration python web app
#
# chkconfig:   55 25
# description: monit remote configuration python web app  
#            

### BEGIN INIT INFO
# Provides: monit-remote
# Required-Start: 
# Required-Stop: 
# Should-Start: 
# Should-Stop: 
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description:  monit remote configuration python web app 
# Description:  monit remote configuration python web app     
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/python"
cwd="/usr/share/monit-remote"
script="/usr/share/monit-remote/app.py"
prog="monit-remote"
pid_file="/var/run/monit-remote.pid"
stdout_log="/var/log/monit-remote/monit-remote.out"
stderr_log="/var/log/monit-remote/monit-remote.err"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon daemonize -o ${stdout_log} -e ${stderr_log} -p ${pid_file} -c ${cwd} ${exec} ${script} $PORT
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pid_file}
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    pid=$(pidofproc -p ${pid_file} ${prog})
    if [ $? -eq 0 ]; then
        echo "${prog} (pid ${pid}) is running..."
        return 0
    else
        if [ -e $lockfile ]; then
            echo "${prog} dead but lockfile exists"
            return 2
        else
            echo "${prog} is stopped"
            return 1
        fi
    fi
}

rh_status_q() {
  rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
